resolver: snapshot.yaml

packages:
  - code/base
  - code/config
  - code/network
  - code/prelude

  - code/demo

ghc-options:
  "$locals": -Wall
             -Wincomplete-uni-patterns
             -Wincomplete-record-updates
