resolver: snapshot.yaml

packages:
  - code/base
  - code/config
  - code/crypto
  - code/network
  - code/prelude

  - code/demo

ghc-options:
  "$locals": -Wall
             -Wincomplete-uni-patterns
             -Wincomplete-record-updates

nix:
  packages:
    - icu
