resolver: snapshot.yaml

extra-deps: []  # Please, use snapshot.yaml

packages:
  - code/async
  - code/base
  - code/config
  - code/crypto
  - code/log
  - code/network
  - code/prelude

  - code/demo

nix:
  shell-file: shell.nix

ghc-options:
  "$locals": -Wall
             -Wincomplete-uni-patterns
             -Wincomplete-record-updates
