resolver: snapshot.yaml

packages:
  - code/base
  - code/network

nix:
  shell-file: shell-stack.nix

ghc-options:
  "$locals": -Wall
             -Wincomplete-uni-patterns
             -Wincomplete-record-updates
             -Wmissing-import-lists
