resolver: snapshot.yaml

packages:
  - code/base
  - code/network

ghc-options:
  "$locals": -Wall
             -Wincomplete-uni-patterns
             -Wincomplete-record-updates
             -Wmissing-import-lists
