name: loot-demo

library:
  source-dirs: lib

  dependencies:
    - base-noprelude

    - loot-base
    - loot-config

executables:
  loot-demo:
    source-dirs: app
    main: Main.hs

    dependencies:
      - base-noprelude

      - loot-demo

      - loot-base
      - loot-config
      - yaml

ghc-options:
  - -Wall
