<<: !include "../base/hpack/lib.yaml"

name: loot-network

dependencies:
- async-combinators
- base >= 4.7 && < 5
- universum
- log-warper
- async
- HUnit
- unliftio-core
- unliftio
- unordered-containers
- bytestring
- kan-extensions
- list-t
- fmt
- network
- network-transport
- network-transport-tcp
- stm-containers
- cryptonite
- transformers
- mtl
- hashable
- serialise
- stm
- tasty
- tasty-hunit

library:
  source-dirs: src

tests:
  loot-network-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - loot-network
