<<: !include "../base/hpack/lib.yaml"

dependencies:
- async
- async-combinators
- base >= 4.7 && < 5
- bytestring
- cryptonite
- fmt
- hashable
- HUnit
- log-warper
- list-t
- network
- network-transport
- network-transport-tcp
- transformers
- mtl
- serialise
- stm
- stm-containers
- tasty
- tasty-hunit
- universum
- unliftio-core
- unliftio
- unordered-containers

library:
  source-dirs: src

name: loot-network

tests:
  loot-network-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - loot-network
